




// player one and player two objects below
// both have 'characters' arrays that are populated with characters when game starts
// when attacks take place

 var playerOne = {
   name : 'Player One',
   characters : [
      pOneWizard = {
        name : 'Player One Wizard',
        img : '<img src=\'http://i.imgur.com/kr285Wm.png\'>',
        moveRate : 2,
        attackProximity : 3,
        attackDamage : 1,
        hitPoints : 7
      },
      pOneAssassin = {
        name : 'Player One Assassin',
        img : '<img src=\'http://i.imgur.com/Lm5TnEF.png\'>',
        moveRate : 3,
        attackProximity : 1,
        attackDamage : 1,
        hitPoints : 5
      },
      pOneJuggernaut = {
        name : 'Player One Juggernaut',
        img : '<img src=\'http://i.imgur.com/vGUprxO.png>\'>',
        moveRate : 1,
        attackProximity : 1,
        attackDamage : 2,
        hitPoints : 9
      }
    ]
 };

 var playerTwo = {
   name : 'Player_Two',
   characters : [
      pTwoWizard = {
        name : 'Player Two Wizard',
        img : '<img src=\'http://i.imgur.com/KFSlZsV.png\'>',
        moveRate : 2,
        attackProximity : 3,
        attackDamage : 1,
        hitPoints : 7
      },
      pTwoAssassin = {
        name : 'Player Two Assassin',
        img : '<img src=\'http://i.imgur.com/80LqFIt.png\'>',
        moveRate : 3,
        attackProximity : 1,
        attackDamage : 1,
        hitPoints : 5
      },
      pTwoJuggernaut = {
        name : 'Player Two Juggernaut',
        img : '<img src=\'http://i.imgur.com/gbcDNuD.png\'>',
        moveRate : 1,
        attackProximity : 1,
        attackDamage : 2,
        hitPoints : 9
      }
    ]
 };

 var p1Wizard = playerOne.characters[0].img;
 var p1Assassin = playerOne.characters[1].img;
 var p1Juggernaut = playerOne.characters[2].img;

 var p2Wizard = playerTwo.characters[0].img;
 var p2Assassin = playerTwo.characters[1].img;
 var p2Juggernaut = playerTwo.characters[2].img;


 var $RedWizard = playerOne.characters[0].img;
$('td').on('click', function(){
  console.log(this.id + ' has been clicked');
});

// var $pOneWizardImage = $('<img>');
// $pOneWizardImage.attr('src', $RedWizard);
// console.log($pOneWizardImage);



$('#Row2-Column0').append(p1Wizard);
$('#Row3-Column1').append(p1Juggernaut);
$('#Row4-Column0').append(p1Assassin);

$('#Row2-Column12').append(p2Wizard);
$('#Row3-Column11').append(p2Juggernaut);
$('#Row4-Column12').append(p2Assassin);

var playerMove = function() {

}



// // Character constructor below

// var Character = function(moveRate, attackProximity, attackDamage, hitPoints ) {
//   this.characterMoveRate = moveRate;
//   this.characterAttackProximity = attackProximity;
//   this.characterAttackDamage = attackDamage;
//   this.characterHitPoints = hitPoints;
// };

// // Characters generated by above Character constructor
// // after each one is generated, they are pushed into the playerOne and playerTwo object arrays
// // when a character is killed by 'hitPoints < 1' then they are removed from the array
// // when an array is emptied during play, then game is over
// // player with an array that still contains character objects wins the game

// var pOneAssassin = new Character(3, 1, 1, 5);
// playerOne.characters.push(pOneAssassin);

// var pOneJuggernaut = new Character(1, 1, 2, 9);
// playerOne.characters.push(pOneJuggernaut);

// var pOneWizard = new Character(2, 3, 1, 7);
// playerOne.characters.push(pOneWizard);



// var move = function(character) {

//     // character moves
//     // check for attack opportunity within threshold
//     // if yes, then call attack function here

// };


// var attack = function {
//   // if opponent is in range
//   //   then attack
//   //
// }
// // // Player prototypes

// // Character.prototype.player


// // Move logic


// // Attack logic



// characters = (characters.indexOf('wizard')
//   return index
