// Character builder object constructor
// take a look at how to embed player 1 or player 2 meta data in
// each of the characters for winning condition check



var Character = function(moveRate, attackProximity, attackRate, hitPoints ) {
  this.characterMoveRate = moveRate;
  this.characterAttackProximity = attackProximity;
  this.characterAttackRate = attackRate;
  this.characterHitPoints = hitPoints;
};

// Characters generated by above Character constructor
assassin = new Character(3, 1, 1, 5);

juggernaut = new Character(1, 1, 2, 9);

wizard = new Character(2, 3, 1, 7);


// Player prototypes

Character.prototype.player


// Move logic


// Attack logic
